apiVersion: v1
kind: Secret
metadata:
  name: private-ws-stack-dados-k8s
  namespace: gitops
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    url: https://fapinheiro@github.com/fapinheiro/ws-stack-dados-k8s
    password: #MY_GITHUB_ACCESS_TOKEN#
    username: #MY_GITHUB_USERNAME#